# Site settings
title: kep3d
email: ikep3d@gmail.com
url: https://kep3d.github.io
description: "Full Stack Software Engineer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: kep3d

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/kep3d

# Build settings
markdown: kramdown
permalink: pretty
